services:
  app:
    container_name: go_container
    build: ./
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./:/go/src/app
  db:
    container_name: database_container
    image: ghcr.io/takakiaraki09/example-k8s-database:latest
    tty: true
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3300:3306"
    # environment:
    #   - DB_PORT=3311
    #   - DB_HOST=127.0.0.1
    #   - DB_USER=root
    #   - DB_PASSWORD=root
volumes:
  go-db-volume:

