services:
  app:
    container_name: go_container
    build: ./
    depends_on:
      - db
    ports:
      - 8080:8080
    tty: true
    environment:
      - DB_PORT=3306
      - DB_HOST=database_container
      - DB_USER=root
      - DB_PASSWORD=root
    volumes:
      - ./:/go/src/app
    networks:
      - network1
  db:
    container_name: database_container
    image: ghcr.io/takakiaraki09/example-k8s-database:latest
    tty: true
    environment:
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3300:3306"
    networks:
      - network1
volumes:
  go-db-volume:

networks:
  network1:
