# ref https://qiita.com/kazuki43zoo/items/7d6771f9d81a2dfd3755
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  strategy:
    # typeに関しての説明 https://qiita.com/mochizuki875/items/239c0e93c30f720e687e#kuberbnetes%E3%81%AE%E3%82%A2%E3%83%83%E3%83%97%E3%83%87%E3%83%BC%E3%83%88%E6%88%A6%E7%95%A5
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: ./Dockerfile
          name: mysql
          resources:
          env:
            - name: MYSQL_USER
              value: devuser
            - name: MYSQL_PASSWORD
              value: devuser
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: LANG
              value: C.UTF-8
          ports:
            - containerPort: 3306
              name: mysql

