// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID uint32 `json:"userId"`
}

type Query struct {
}

type Todo struct {
	ID     uint32 `json:"id"`
	Text   string `json:"text"`
	Done   bool   `json:"done"`
	UserID uint32 `json:"userId"`
	User   *User  `json:"user"`
}

type User struct {
	ID    uint32  `json:"id"`
	Name  string  `json:"name"`
	Todos []*Todo `json:"todos"`
}
