// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type ExampleTable struct {
	ID    uint32
	Title sql.NullString
	Hoge  sql.NullString
}
