package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"

	"github.com/TakakiAraki09/k8s-lesson/internal/generated"
	model1 "github.com/TakakiAraki09/k8s-lesson/internal/model"
)

// Todos is the resolver for the todos field.
func (r *userResolver) Todos(ctx context.Context, obj *model1.User) ([]*model1.Todo, error) {
	return r.Service.GetTodoByUserId(ctx, obj.ID)
}

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
